language: python
python:
  - "2.7"
  - "3.4"
env:
  - GDAL_VERSION=2.1
install:
  - "pip install coveralls"
  - "pip install -e .[test]"
script:
  - py.test
  - coverage run --source=fio_area -m py.test
after_success:
  - coveralls
sudo: false
